controllers:
    resource: ../src/Controller/
    type: annotation

kernel:
    resource: ../src/Kernel.php
    type: annotation

app_TaskController:
    path: /tasks
    controller: App\Controller\TaskController::index

app_Register:
    path: /register
    controller: App\Controller\UserController::register
