controllers:
    resource: ../src/Controller/
    type: annotation

kernel:
    resource: ../src/Kernel.php
    type: annotation

app_Home:
    path: /
    controller: App\Controller\HomeController::index

app_TaskController:
    path: /tasks
    controller: App\Controller\TaskController::index

app_Register:
    path: /register
    controller: App\Controller\UserController::register

login:
    path: /login
    controller: App\Controller\UserController::login

logout:
    path: /logout
