controllers:
    resource: ../src/Controller/
    type: annotation

kernel:
    resource: ../src/Kernel.php
    type: annotation

app_Register:
    path: /register
    controller: App\Controller\UserController::register

app_TaskList:
    path: /tasks
    controller: App\Controller\HomeController::index

login:
    path: /
    controller: App\Controller\UserController::login

logout:
    path: /logout

task_edit:
    path: /task/edit/{id}
    controller: App\Controller\TaskController::edit

task_delete:
    path: /task/delete/{id}
    controller: App\Controller\TaskController::delete

task_create:
    path: /task/create
    controller: App\Controller\TaskController::creation

task_detail:
    path: /task/detail/{id}
    controller: App\Controller\TaskController::detail

mytasks:
    path: /mytasks
    controller: App\Controller\UserController::myTasks
